### ISSUE TITLE
Add Tooltip to Zoom Icon

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-plugin-zoom#10]
Other icons in the channel header have a tooltip when a user hover overs them for a few seconds, but the Zoom plugin doesn't have one. This should be added.

**Comment by dhadiseputro** [comment]
I think the current header with the video recorder icon have a tooltip saying "Start Zoom Meeting".
Issue can be close?

**Comment by dhadiseputro** [comment]
@hanzei bump

**Comment by hanzei** [comment]
Thanks for the reminder @dhadiseputro :+1: I can confirm that this is fixed
