### ISSUE TITLE
Zoom JWT/Legacy: Accept webhook events in new Format so meeting state is updated

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-zoom#108]
We should support the new event payloads that get generated by the Zoom JWT app. Currently, we support Legacy formatted webhooks, which required two apps to be setup - but this has recently stopped working.

**Comment by larkox** [comment]
JWT webhooks work the same way as OAuth webhooks. Therefore, the implementation for #107 should work for this issue too.
