### ISSUE TITLE
Avoid starting meetings in crowded channels when not intended

### ISSUE THREAD

**Issue by agarciamontoro** [mattermost/mattermost-plugin-zoom#114]
Today, I misclicked in the header's Zoom plugin button and the plugin posted a link to my personal meeting room in a channel with more than 5000 members.

My feature request is to add a confirmation dialog that prevents users to start meetings by mistake. But @levb also suggested that we could also add a blacklist with channels where starting a Zoom meeting is not allowed.

**Comment by levb** [comment]
Suggest 2 things:
1) we can add a plugin-level (config) or user-level (/command?) way to disable the button in specific channels
2) I also ❤️ the idea of popping a dialog if the number of channel members is >X, where X can be configurable.

**Comment by aaronrothschild** [comment]
> 2) I also ❤️ the idea of popping a dialog if the number of channel members is >X, where X can be configurable.

We made it 1 click because people don't like having to confirm something for every meeting. This is a good compromise IMO. 

I like this as well, similar to how we warn users now when using `@` mentions in a large channel.

**Comment by larkox** [comment]
It is not a real solution, but I have made a PR that will post the meetings as the user, so you can delete a meeting if you misclick.

**Comment by agarciamontoro** [comment]
I think it is actually a good solution, @larkox!

**Comment by hanzei** [comment]
Discussed offline: Deleting the post is a fine solution for can accidentally created meeting.
