### ISSUE TITLE
Add codecov.io webhook to github repo

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-zoom#117]
The badge will be added in this PR.

To do this, an admin to this repo needs to visit https://codecov.io/gh/jfrerich/mattermost-plugin-zoom/settings and click 
![image](https://user-images.githubusercontent.com/7575921/83761755-57d44880-a63c-11ea-9fb8-b044899e964d.png)

**Comment by hanzei** [comment]
Same questions as in https://github.com/mattermost/mattermost-plugin-antivirus/issues/19#issuecomment-634498041

**Comment by hanzei** [comment]
@levb Could you please enable the webhook?

**Comment by larkox** [comment]
Since the coverage badge is working fine, I suppose this can be closed.
