### ISSUE TITLE
Add info to Zoom oAuth UI

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#121]
We should add info to the Zoom configuration screen for Oauth

1. Add `Beta` label beside oAuth config enable option
2. There is currently a label that reads `Please enable only either one of OAuth based or Password base authentication.`  
This should be updated to also explain about the mapping. Please change it to `Please enable only either OAuth based or Password base authentication. If you are currently using a JWT Zoom application and switch to oAuth, users will need to connect again using oAuth the first time they create a meeting.`

**Comment by DHaussermann** [comment]
@aaronrothschild can you approve (or change) the label text for 2. This may sound a bit clunky but I wanted to keep it short since it's text in the admin UI.

**Comment by aaronrothschild** [comment]
Some changes:
 `Only Enable OAuth OR Password based authentication. Not both. If you are currently using a JWT Zoom application and switch to OAuth, all users will need to connect their Zoom account using OAuth the next time they try to start a meeting.`

**Comment by terafirmanz** [comment]
Should some text also be added to explain why one might pick either option? Feels like a decision is left to the server admin with no context as to why they need to make a choice or the implications of it.

**Comment by terafirmanz** [comment]
> Should some text also be added to explain why one might pick either option? Feels like a decision is left to the server admin with no context as to why they need to make a choice or the implications of it.

I see there is a gitbook doc now but neither the readme nor the plugin admin screens mentions this. Maybe a simple link will help people to both decide and setup the plugin.

**Comment by larkox** [comment]
Thanks for the idea @terafirmanz . A update to the README will be coming soon, that will directly link to the gitbook.

Do you think a "more information" link to the gitbook next tot he decision would be enough? What do you think, @aaronrothschild ?

**Comment by aaronrothschild** [comment]
> Do you think a "more information" link to the gitbook next to the decision would be enough? What do you think, @aaronrothschild ?

I think that should be fine, most people don't necessarily care about why.

**Comment by terafirmanz** [comment]
> Thanks for the idea @terafirmanz . A update to the README will be coming soon, that will directly link to the gitbook.
> 
> Do you think a "more information" link to the gitbook next tot he decision would be enough? What do you think, @aaronrothschild ?

Yes that works fine. The docs give detail as to what each choice means for the user.
