### ISSUE TITLE
Disconnect slash command should not be available when JWT is being used

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#127]
We have added a slash command for oAuth `/zoom disconnect`. This functions as desired when using oAuth but, the command is not applicable when password based authentication is enabled.

Users will still see it in the help and get an error if they attempt to use it. I don't know why they would try since there is no connect/disconnect mechanism at a user level for JWT but it can be attempted. 

![Screen Shot 2020-06-12 at 10 59 21 AM](https://user-images.githubusercontent.com/35588783/84522502-bdf84580-aca4-11ea-81f3-2e705d15e80b.png)

**Comment by larkox** [comment]
Will fix.
