### ISSUE TITLE
Add support for meeting ended webhook events with oAuth Zoom apps

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#128]
When using an oAuth Zoom application, the post will not be updated to reflect that the meeting has ended. 
Additionally there is not setup info for this documented in the oAuth section which leads me to believe this may not yet be implemented. 

![ZoomOauthWebhook](https://user-images.githubusercontent.com/35588783/84525379-8b048080-aca9-11ea-87aa-b7479b2b3691.PNG)

Steps:
1. Create an oAuth Zoom app as per gitbook info
2. Add a subscription for Meeting ended
3. From Mattermost Launch a meeting 
4. End meeting for all
Observed: post is not updated.

**Comment by DHaussermann** [comment]
@larkox I'm not sure if this is a bug that requires more investigation to see an error or if this was never implemented.

**Comment by larkox** [comment]
The documentation is not in the OAuth section because it is (or should be) in its own section (it is the same for JWT and OAuth).

Not sure why it is failing. I need to double check. It should be working.

**Comment by larkox** [comment]
Bug found. This only happens when creating the meeting via slash command. If you create the meeting via the UI button, the meeting updates without any problem. Will fix.
