### ISSUE TITLE
Mattermost 5.5.1 missing bundled zoom plugin, upload of 1.0.2 does not work

### ISSUE THREAD

**Issue by vpecinka** [mattermost/mattermost-plugin-zoom#13]
After upgrade to MM 5.5.1 I noticed there is no Zoom plugin anymore in the server release.

When I try to upload release 1.0.2, I get this error when using it:

```
{"level":"error","ts":1544639706.6505132,"caller":"app/plugin_requests.go:33","msg":"Access to route for non-existent plugin","missing_plugin_id":"zoom","error":"plugin not found: zoom"}
```

I guess it has something to do with the structure of tar.gz archive...

When I use pre-packed tarball from MM 5.5.0 release with 1.0.1 plugin, it works.

**Comment by hanzei** [comment]
> After upgrade to MM 5.5.1 I noticed there is no Zoom plugin anymore in the server release.

Thanks you very much for the report. I created a PR fix this this: https://github.com/mattermost/mattermost-server/pull/9994.

> When I try to upload release 1.0.2, I get this error when using it:

Would you please open a new issue for this please? Could you also share more log messages?

**Comment by hanzei** [comment]
Closing this one as https://github.com/mattermost/mattermost-server/pull/9994 got merged.
