### ISSUE TITLE
OAuth not supported anymore?

### ISSUE THREAD

**Issue by robormondsimpro** [mattermost/mattermost-plugin-zoom#131]
I'm trying to set up our zoom plugin to use oauth but I don't see the option in the zoom settings page as per screenshot.

I've made sure that mattermost is configured true for "Enable OAuth 2.0 Service Provider".  Not sure what else to check.

I am running version 1.3.1 of zoom plugin, with mattermost version 5.21

![Capture](https://user-images.githubusercontent.com/22141727/84618630-184c0d00-af16-11ea-86a9-479c92bcf021.PNG)

**Comment by robormondsimpro** [comment]
Also noticed that when I try to browse to 
https://[mm url]/plugins/zoom/oauth2/complete?code=mvd1qF6TwW_Fzt3YddyQeyCehyACotZHg 
it returns a 404 error

**Comment by larkox** [comment]
Sorry for the inconvenience. The documentations is slightly ahead of the latest version. We will release soon Zoom with OAuth (v1.4.0). I will keep you posted.
