### ISSUE TITLE
Refactor zoom OAuth to use the client model

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-zoom#136]
JWT uses a client model implemented on `server/zoom/`. On the other hand, the same functions for OAuth are scattered through `server/plugin.go`. This PR has the following objectives:
- Create a new client to handle OAuth requests
- Move and refactor the client related functions from plugin.go to `server/zoom/`.
- Refactor the general code to use the client functions.

If there is any question about the task, feel free to contact through here.

**Comment by utkuufuk** [comment]
I'll take this one.
