### ISSUE TITLE
If user's email is not valid for JWT Zoom, launching Zoom from the icon will show oAuth link  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#137]
If a user has an invalid email to use the JWT app, trying to launch via the plugin icon will show oAuth connection link. 
Using Zoom start works normally and shows the invalid email message

Steps:
- Install Zoom pluigin and configure both authentication methods
- Set JWT to True and oAuth to False
- Login as a user with invalid email to use JWT app
- Type `/zoom start`
- Note the expected message that email is invalid
- Click the Zoom icon
**Observed**: oAuth connection link is shown
**Expected**: Message that email is invalid

**Comment by larkox** [comment]
Will fix

**Comment by larkox** [comment]
@DHaussermann Heads up that there is already a PR to fix this.
