### ISSUE TITLE
Posts do not update when meeting ends for oAuth and slash command launch 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#140]
When oAuth is enabled and I use `/zoom start` to launch a meeting, when the meeting ends the post does not get updated. 

This issue will only occur when using oAuth and the slash command. 

Reproduces on version bump branch https://github.com/mattermost/mattermost-plugin-zoom/pull/123/commits/118f1bd126ca9ed718be4dab564dc5b13a9059d5

Steps:
- Install Zoom and configure oAuth
- Launch a zoom meeting with `/zoom start` 
- End meeting for all
**Observed**: Post did not update to reflect that meeting has ended.

**Comment by DHaussermann** [comment]
@larkox I thought this was working in https://github.com/mattermost/mattermost-plugin-zoom/pull/134 
Maybe I missed a bug in testing or a more recent change has caused an issue?

**Comment by larkox** [comment]
@DHaussermann Yes, it should be working in #134. The problem is that #134 is still not merged :sweat_smile:
