### ISSUE TITLE
Zoom Icon is sometimes missing from header in 5.23.2 and earlier

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#143]
In some cases the Zoom icon is missing from the header. This does not repro on any of my testing servers for zoom but, I see it if I spin up a fresh server.

I can't quite figure out what's happening here. Even in incognito mode my test server show the icon correctly. (Possibly something is cached on the server from a previous PR which hides the bug) . But here is an affected server https://dkh-zoom-temp5.test.mattermost.cloud

Steps:
- Create a new server
- Install Zoom 1.4 and enable
**Observed** Icon is missing from the channel header
![Zoom-icon](https://user-images.githubusercontent.com/35588783/86292626-15f8dc80-bbbf-11ea-88a3-ba8654ace76f.PNG)

**Comment by DHaussermann** [comment]
@larkox are you able to see if this is complicated to fix? I'm curious because for affected servers, this is a very visible bug.
cc @aaronrothschild

**Comment by larkox** [comment]
May have to do with the version of the server. We are using a font that may not be in all server versions.

Not sure how to handle this if not by always using the SVG.
cc @asaadmahmood

**Comment by DHaussermann** [comment]
Thanks @larkox  after some testing it seems you're correct. The bug repros on any version before `v5.24.0'
