### ISSUE TITLE
Decide whether to use PMI or not on instant meetings

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-zoom#154]
After #147 is merged, you will be able to create meetings with new IDs.

We would like to add a user setting set by slash commands (`/zoom setting usePMI [true/false/ask]`) to allow the user decide whether to use its PMI on instant meetings.

If the setting is set to ask, when it is going to create a meeting, they will receive an ephemeral message where they can choose to use the PMI or the new ID.

**Comment by lantrungseo** [comment]
I want to try this issue. Thanks a lot!

**Comment by lantrungseo** [comment]
@larkox I have a question: How can we send ephemeral post to user using `postTypeZoom` component? I tried but `plugin.SendEphemeralPost(userID, post)` doesn't render anything except `Message`. Or do I need to use other methods?

**Comment by larkox** [comment]
Answered here: https://github.com/mattermost/mattermost-plugin-zoom/pull/181#issuecomment-726236418
