### ISSUE TITLE
Clicking start meeting button crashes on Daily

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#156]
This has only happened to me once. Sometimes it seems that nothing happens when the button is clicked.

Error is happening on line 6 below. `main.1c074abf2550c153bb77.js:489 TypeError: Cannot read property 'replace' of undefined`. It looks like code from `mattermost-webapp`

```js
 function U(e, t, r, n, a, o) {
    const {formatMessage: i, formatTime: s, formatDate: u} = a;
    let c, d, l = e.message;
    for (const e of Object.keys(E.b)) {
        const t = E.b[e];
        l = l.replace(t, ":".concat(e, ":"))
    }
    for (; null !== (c = E.a.exec(l)); )
        o.has(c[2]) && (l = l.replace(c[0], "".concat(c[2].replace(/_/g, " "), " emoji")));
    d = e.root_id ? i({
        id: "post.ariaLabel.replyMessage",
        defaultMessage: "At {time} {date}, {authorName} replied, {message}"
    }, {
        authorName: t,
        time: s(e.create_at),
        date: u(e.create_at, {
            weekday: "long",
            month: "long",
            day: "numeric"
        }),
        message: l
    }) : i({
        id: "post.ariaLabel.message",
        defaultMessage: "At {time} {date}, {authorName} wrote, {message}"
    }, {
        authorName: t,
        time: s(e.create_at),
        date: u(e.create_at, {
            weekday: "long",
            month: "long",
            day: "numeric"
        }),
        message: l
});
```

![image](https://user-images.githubusercontent.com/6913320/91221762-207db100-e6ec-11ea-84ed-ad8b723fa4d2.png)

**Comment by hanzei** [comment]
@larkox Could you please take a look at this once you are back? Maybe you can spot if this should be fixed in the webapp or in the plugin.

**Comment by larkox** [comment]
It is hard to guess the problem without a reliable way to reproduce it. I know there is a different error that has to do with posting a jitsi meeting and right after a zoom meeting, but there is a PR for that.

This seems something different, but at the same time, I have no idea what might be causing it.

**Comment by Willyfrog** [comment]
[related Jira ticket](https://mattermost.atlassian.net/browse/MM-28680)

also, while investigating I noticed that community says that the command is not registered, although it does provide autocompletion. will be interesting to check that as well once the patch is uploaded to the server

**Comment by mickmister** [comment]
@Willyfrog WHen it says the command is not registered, either:
- the plugin's server portion crashed recently, and has not been picked up by the plugin hralth check job
- the plugin was disabled either manually or due to the plugin health check job

I'm not sure how the autocomplete comes into play when a plugin crashes or is disabled. @iomodo Do you have any thoughts on this?

**Comment by iomodo** [comment]
@Willyfrog this can happen if plugin was crushed unexpectedly and slash commands where not unregistered. Is it still reproducible?

**Comment by Willyfrog** [comment]
when that happened, I think the plugin was crashing, so yes I can confirm your suspicions, but I don't think it is currently happening
