### ISSUE TITLE
After update from 1.3.1 to 1.4.1 zoom posts get not updated anymore

### ISSUE THREAD

**Issue by balta3** [mattermost/mattermost-plugin-zoom#157]
Two days ago we upgraded mattermost and all plugins to the current version, in this case from 1.3.1 (I think) to 1.4.1. Before the update the zoom plugin was working without any problems, but after the update new posts about zoom meetings are not updated anymore if the meeting was closed. In the access log I see that the webhook returns a 400, but in the mattermost log there seems to be nothing logged about the call at all. There are two requests by zoom for every webhook, one GET and one POST, both are returned with 400.

I've seen some issues and PRs about a changed format from form-data to json for the webhook in this release, is it possible that zoom is still using the old format for our account?

Is it safe to downgrade the plugin until this is resolved?

**Comment by larkox** [comment]
Hi @balta3 , thank you for reaching us. How do you have configured the webhooks? Please, take a look at the documentation [here](https://mattermost.gitbook.io/plugin-zoom/) and make sure you have set up the webhooks correctly.

The problem might be indeed because of the drop of support on legacy webhooks (in theory, Zoom has also dropped the support for them).

If you feel everything is done correctly, please, give us more information, or contact me directly on [Mattermost Community](https://community.mattermost.com/core/messages/@daniel.espino.garcia).

**Comment by balta3** [comment]
Thanks for the fast reply :+1: 

I already looked at the documentation but the webhook documentation is only described for OAuth apps, for my old configured app the screen looks different from the documentation.
![Screenshot_2020-08-28 App Marketplace](https://user-images.githubusercontent.com/3757994/91554504-8e65ea80-e92f-11ea-8875-e399b05c8c39.png)

**Comment by larkox** [comment]
I see. That is the webhook configured App. You probably have also a JWT or OAuth app configured. Am I right? On the configuration of those apps, you should see the feature menu, where you can add webhooks. Tell me if you don't or if you have any other kind of app installed.

**Comment by balta3** [comment]
I removed the webhook only app and added a webhook feature to the existing JWT app and the update is working again. Thanks for this :+1: 

Perhaps you should add some notification to the releases notes about this, as anybody who configured this integration right after mattermost announcement of the Zoom integration will have an old setup like we have.

**Comment by larkox** [comment]
@aaronrothschild :point_up:

**Comment by aaronrothschild** [comment]
@justinegeffen Can we add an update to the docs basically stating:
- If you have previously installed Zoom before v1.4, you likely have a "Webhook" type of app in Zoom configured
- Once switched over to OAuth, the Zoom admin should disable/remove the "Webhook" only app that existed prior to creating the new OAuth zoom App.

**Comment by justinegeffen** [comment]
Thanks, @aaronrothschild, I'm on it.
