### ISSUE TITLE
Add screenshot to the README

### ISSUE THREAD

**Issue by jespino** [mattermost/mattermost-plugin-zoom#167]

**Comment by larkox** [comment]
It would be interesting to update the screenshots on the Gitbook too, since they show an outdated UI of Mattermost.

**Comment by AugustasV** [comment]
Oh I checked this task and understood that I couldn't do it because I don't have paid zoom account...

**Comment by larkox** [comment]
@AugustasV I think you should be able to deal with everything needed for this task with a developer account. Am I wrong?

**Comment by AugustasV** [comment]
@larkox I saw it in official documentation that I must have paid account https://mattermost.gitbook.io/plugin-zoom/installation/mattermost-setup I tried with free account Developer credentials but it didn't work.

**Comment by larkox** [comment]
@AugustasV If I am not mistaken, a paid account is needed to "properly use" the plugin. With a developer account, you will be the only one that can create meetings (there are no more people in your account). But that should be enough to deal with all the functionality you have to access. Am I missing anything? What exactly didn't work for you?

**Comment by larkox** [comment]
I have seen that @mickmister has uploaded several screenshots to use on the new installation flow (here is the PR https://github.com/mattermost/mattermost-plugin-zoom/pull/249/files ).

Maybe you can use those.
