### ISSUE TITLE
unable to login with JWT

### ISSUE THREAD

**Issue by umlaeute** [mattermost/mattermost-plugin-zoom#176]
I've setup the zoom-integration with JWT authentication, but whenever I try to start a new meeting I get an error from the but:

> We could not verify your Mattermost account in Zoom. Please ensure that your Mattermost email address given.name@myuni.ac.test matches your Zoom login email address.

In the mattermost logs i get:

~~~
2020-10-13_11:56:20.18800 {"level":"warn","ts":1602590180.1878636,"caller":"mlog/sugar.go:27","msg":"failed to execute command","plugin_id":"zoom","error":"{\"code\":1001,\"message\":\"User does not exist: given.name@myuni.ac.test.\"}"}
~~~

system:
- mattermost 5.26.2 (CE; as shipped with gitlab/omnibus)
- mattermost-plugin-zoom 1.4.1

I have followed the [documentation](https://mattermost.gitbook.io/plugin-zoom/installation/zoom-configuration/) to setup the plugin with JWT authentication.
On the zoom-side, I've created the application with our institute's "Zoom Pro" account, that goes by the email `zoom@institute.test`.

the users in mattermost get authenticated via JWT against our gitlab server, which in turn authenticates against the university's LDAP-server. the user emails follow the scheme `given.name@myuni.ac.test`.

none of the users authenticating via LDAP are connected to our "Zoom Pro" account (and they have a different domain, if that matters).

what could possibly go wrong?

**Comment by larkox** [comment]
JWT relays on Mattermost configured email to do the authentication. If your email is different between Mattermost and Zoom, and you cannot change that, you need to use OAuth authentication.

**Comment by umlaeute** [comment]
@larkox thanks for the quick reply, but see #177 :frowning_face:

**Comment by umlaeute** [comment]
what i did forget to add is, however: I do have a zoom user-account `given.name@myuni.ac.test`.

i guess that the developer who creates the zoom-JWT-app, does not necessarily have to have the *same* email address as the mattermost user who wants to initiate a meeting.
(otherwise: each and every user would need a different zoom-JWT-app, which i think doesn't make sense)

**Comment by umlaeute** [comment]
> JWT relays on Mattermost configured email to do the authentication. If your email is different between Mattermost and Zoom, and you cannot change that, you need to use OAuth authentication.

hmm.
the idea was, that the email that comes from mattermost (`given.name@myuni.ac.test`) is used for authentication against zoom (there *is* a zoom-account `given.name@myuni.ac.test`).
however, as said in #177 , the zoom account `given.name@myuni.ac.test` is *not associated* with the company (PRO) account `zoom@institute.test`.

is this the root of the problem?

is it a requirement that all accounts that want to initiate a meeting
- to be associated with the developer account that created the application
OR
-  to be on a "PRO" (or better) plan themselves?

**Comment by umlaeute** [comment]
thanks for confirming.

is that requirement the same for JWT and OAuth?

**Comment by umlaeute** [comment]
ah i just saw https://github.com/mattermost/mattermost-plugin-zoom/issues/177#issuecomment-707759121 which basically confirms that each and every user who wants to initiate a zoom-meeting from within mattermost  **must** be associated with ("member of") the zoom-account that created the zoom-application.

is this a limitation of zoom? or some design decision of the integration?
(for me, the current behaviour unfortunately makes the zoom-integration practically useless, at lest medium-term :sigh:)

**Comment by larkox** [comment]
It is a limitation on Zoom side. In theory, an app "published in the Zoom marketplace" can go around this limitation, but I have not seen yet any actual implementation of that.

**Comment by umlaeute** [comment]
thanks.

if i missed this information in the documentation, then *mea culpa*.
if instead the documentation misses this piece of information, i would suggest to add it.

**Comment by larkox** [comment]
@justinegeffen :point_up:

**Comment by justinegeffen** [comment]
Thanks, @larkox! Thanks @umlaeute for raising this. Would you be open to updating the documentation with your feedback and submitting a pull request? If this will be your first PR please let me know and I'll be more than happy to assist. :)
