### ISSUE TITLE
unable to login with Oauth

### ISSUE THREAD

**Issue by umlaeute** [mattermost/mattermost-plugin-zoom#177]
given my troubles with JWT (see #176) i also tried using `OAuth` - no luck either!

I've setup the zoom-integration with Oauth authentication, but whenever I try to start a new meeting I get a message `Click here to link your Zoom account.` (which is expected), but once i click the link I get:

![zoom-oauth](https://user-images.githubusercontent.com/214034/95858792-ec268880-0d5d-11eb-9ce5-5b2560a859b0.png)

I have followed the [documentation](https://mattermost.gitbook.io/plugin-zoom/installation/zoom-configuration/) to setup the plugin with OAuth authentication.
On the zoom-side, I've created the application with our institute's "Zoom Pro" account, that goes by the email `zoom@institute.test`.

the users in mattermost get authenticated via OAuth against our gitlab server, which in turn authenticates against the university's LDAP-server. the user emails follow the scheme `<givenname>.<surname>@myuni.ac.test`.

none of the users authenticating via LDAP are connected to our "Zoom Pro" account (and they have a different domain, if that matters).

however, my test-user `given.name@myuni.ac.test` does have a zoom-account with that email-address.

what could possibly go wrong?

**Comment by larkox** [comment]
The problem here is that the user account you are trying to log into Zoom during that step is not a Zoom user account associated to the "company account" that created the OAuth App.
You shouldn't receive that screen at first, you should receive a login page. Maybe you are already logged in to Zoom with a different account?

**Comment by umlaeute** [comment]
so i logged out of zoom, and run `/zoom start` in mattermost again:

- the zoom-login page comes up
  - i enter my credentials
- i get the "You cannot authorize this app" error again

**Comment by umlaeute** [comment]
for what it is worth: my zoom-account is only a `BASIC` account (unlike the `Pro` account which was used to create the OAuth-zoom-app)

**Comment by umlaeute** [comment]
> The problem here is that the user account you are trying to log into Zoom during that step is not a Zoom user account associated to the "company account" that created the OAuth App.

so does that mean that `OAuth` authentication *only* works for accounts that are associated with the "company account"?
