### ISSUE TITLE
Add friendly message on disconnect if user is not currently authenticated

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#178]
If a user not authenticated for Zoom uses the disconnect command, they will see an unfriendly message  `Failed to disconnect the user: unexpected end of JSON input`

This should be changed to something like "Your Zoom account is not currently linked"

Steps:
- Enable Zoom plugin and configure it to use oAuth authentication method
- Login as a user who is not authenticated with their Zoom account (or type `/zoom disconnect` on a user who is)
- Type `/zoom disconnect`
Observed: 
![Screen Shot 2020-10-15 at 5 55 56 PM](https://user-images.githubusercontent.com/35588783/96190542-68f96400-0f10-11eb-9ea4-70bb562ff019.png)

**Comment by DHaussermann** [comment]
@hanzei this may make a good Help Wanted issue

**Comment by yash2189** [comment]
Hello I'm new to opensource. could you please tell me whether this message has to be added under `mattermost-plugin-zoom/server/zoom/oauth.go`?

**Comment by larkox** [comment]
Probably the change has to be done in `server/store.go`, near line 65. The idea is to check whether `encoded`is empty (not sure if nil or just an empty list of bytes). That would mean that there is no user registered under that key, and therefore that user is not connected.

**Comment by yash2189** [comment]
Can I try working on this @larkox ?

**Comment by larkox** [comment]
Yes, please, do. Thank you very much for contributing! :tada:

**Comment by yash2189** [comment]
@larkox I have added the changes , can you please tell me how do I install this plugin so that I can test my changes if necessary?

**Comment by larkox** [comment]
Just by typing `make deploy` it should install it in your local mattermost instance. If you don't have set up your mattermost local instance for development, you can find more information here: https://developers.mattermost.com/contribute/getting-started/
If `make deploy` does not work for any reason, you can try `make dist` and upload directly the bundle to your instance.

**Comment by yash2189** [comment]
@larkox Should I be installing the server? I was a bit confused

**Comment by DHaussermann** [comment]
Hi @yash2189 
Sorry I'm not quite sure I understand your question but, once you run `make` both the webapp and server portions of the Zoom plugin will be built into one compiled package. They are not installed seperately. 

Regarding Zoom - you can sign up for developer account here https://marketplace.zoom.us and create an oAuth App that is usable for testing. There is documentation in this Zoom repo that covers how to configure the app.

**Comment by yash2189** [comment]
Can you please review my PR @larkox @DHaussermann ?

**Comment by larkox** [comment]
In order to start developing, you need to setup your development environment. You can get all the information here: https://developers.mattermost.com/contribute/getting-started/
After you have your testing environment set up, you can run `make deploy` on the plugin folder in order to install it. Then you just have to go to the System Console and enable the plugin.
If you have any problem during the process, feel free to contact our team in any of the [Mattermost Community](https://community.mattermost.com) or [me directly](https://community.mattermost.com/core/messages/@daniel.espino.garcia).

**Comment by yash2189** [comment]
Can you please review the changes @larkox on PR #180 ?
