### ISSUE TITLE
Zoom API v1 deprecated; Plugin not functional anymore

### ISSUE THREAD

**Issue by checkaayush** [mattermost/mattermost-plugin-zoom#19]
Refer: https://zoom.github.io/api-v1/
```
Version 2 of the Zoom API was released on November 4th, 2017. Version 1 of the Zoom API is being sunset and will no longer be supported after November 1st, 2018. It is recommended that you start developing with Version 2 of the Zoom API.
```

**Comment by jasonblais** [comment]
@checkaayush Thanks for the report! This plugin indeed uses Zoom API v2 https://github.com/mattermost/mattermost-plugin-zoom/blob/master/server/zoom/client.go#L20

Are you having trouble getting the Zoom plugin to work?

**Comment by checkaayush** [comment]
@jasonblais Sorry, my bad. I just started reading the code and saw use of API v1 here: https://github.com/mattermost/mattermost-plugin-zoom/blob/master/webapp/src/client/client.js#L14

Issue can be closed if that's not the case.

**Comment by jasonblais** [comment]
@checkaayush Aah, nice one. I created a ticket for our team to take a look and fix as needed. The intent is to use v2 throughout the plugin, but maybe this was missed in a couple of places.

https://mattermost.atlassian.net/browse/MM-14704

**Comment by hanzei** [comment]
The plugin maintains an API endpoint and versioned it. The code line mentioned above refers to the API version of the **plugin's** http endpoin  and not the http endpoint of some zoom server. . See https://github.com/mattermost/mattermost-plugin-zoom/blob/master/server/plugin.go#L59-L60 for the called code.

To sum this up: The code is fine and no changes are needed.

FYI: We define the used Zoom API version in https://github.com/mattermost/mattermost-plugin-zoom/blob/master/server/zoom/client.go#L20
