### ISSUE TITLE
Missing configuration options

### ISSUE THREAD

**Issue by Nisutec** [mattermost/mattermost-plugin-zoom#191]
Hello,
I have installed the Zoom Plugin from the Marketplace but in the plugin configuration I can’t find all settings from the documentation. Why is the OAuth option not displayed I have installed the “Zoom 1.3.1 Version”. How I can fix this problem?

configuration screenshot:
https://drops.n-tp.de/E0urN7Jd

**Comment by hanzei** [comment]
Could you please install at least Version v1.4.0 please and re-test?

**Comment by Nisutec** [comment]
After installing Version 1.4.1 it works
