### ISSUE TITLE
Improve explanation message for disabled setting "Enable Personal Meeting ID"

### ISSUE THREAD

**Issue by vmakarenko** [mattermost/mattermost-plugin-zoom#199]
For the moment the plugin redirects to 
![image](https://user-images.githubusercontent.com/4024310/98674506-33059f00-2359-11eb-9c58-fa7fa829f40d.png)
page and gives no idea how to proceed further, e.g. change the setting in https://zoom.us/profile/setting

**Comment by catalintomai** [comment]
FYI: In Zoom one can disable personal meeting Id.

**Comment by larkox** [comment]
What we can do right now is check the PMI to be a valid PMI (!= -1), and if the PMI is invalid, not create the meeting and tell the user to enable PMI.
