### ISSUE TITLE
Support naming the zoom meeting via `/zoom start`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#200]
When the MM user wants to start a meeting, we can allow them to supply a meeting title/topic within the `/zoom start` slash command, like so:

`/zoom start Meeting about the new project requirements`

_Originally posted by @mickmister in https://github.com/mattermost/mattermost-plugin-zoom/pull/147#discussion_r524409386_

**Comment by kott** [comment]
I wouldn't mind taking this on.

**Comment by larkox** [comment]
Thanks @kott for your interest! All yours :smile:
