### ISSUE TITLE
OAuth error on account level authorization with Enterprise Zoom

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-zoom#203]
Hi,
setting up Zoom with user level authentication works. But when I try to set up an account based authentication I get errors:

`2020-12-14T16:16:05.730+0100    warn    mlog/sugar.go:27        failed to execute command       {"plugin_id": "zoom", "error": "error fetching zoom user: Get \"https://api.zoom.us/v2/users/my.name@company.de\": oauth2: cannot fetch token: 401 Unauthorized\nResponse: {\"reason\":\"Invalid Token!\",\"error\":\"invalid_request\"}"}
`

The mail address used by the user (anonymized here) is the same as set up in Zoom.
Might this be related to an **Enterprise Zoom account** we're using? We changed this three days ago from Pro to Enterprise & I'm pretty sure it worked before with account level authentication.

Mattermost config looks like:
`"zoom": {
    "accountlevelapp": true,
    "apikey": "",
    "apisecret": "",
    "enablelegacyauth": false,
    "enableoauth": true,
    "encryptionkey": "sanitized",
    "oauthclientid": "sanitized",
    "oauthclientsecret": "sanitized",
    "webhooksecret": "sanitized",
    "zoomapiurl": null,
    "zoomurl": null
}`

For now, we stay with the user level authentication, which works.

Best

JP

**Comment by larkox** [comment]
@jprusch When setting the "Account Level App", have you gone through the oauth process with the Admin user? In order for this to work you have to:

- Go to the system settings, and set "Account Level App" to true
- Make sure the information you have as OAuth Client ID and OAuth Client Secret is for a Account Level App on Zoom side.
- On Mattermost, as a sysadmin, run `/zoom connect`
- Follow the link and follow the instructions

Once all that is done, it should work.

**Comment by jprusch** [comment]
@larkox Thanks! I think I forgot to unconnect after my first try. Works now with account level settings.
