### ISSUE TITLE
Change wording of post when meeting ends

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#210]
When a zoom meeting ends that was started with the zoom plugin, the post is updated with the phrase:

> I have ended the meeting.

The task here is to change the wording to:

> The meeting has ended.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/rw9mixywr7yf5eoh3zk76uat1w) *by @larkox*._

**Comment by emskaplann** [comment]
I've updated the phrasing as you asked. I'm pretty new to open source contributing, so I hope everything is in place. Thanks!

**Comment by larkox** [comment]
Thanks for the interest @emskaplann . Will give some feedback on the PR :smile:
