### ISSUE TITLE
Start zoom meeting sometimes displays an unauthorized error message

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-zoom#213]
Hi,
we're using Zoom Enterprise with account level authorization. While the Zoom plugin is working like a charm one day, I get errors the next day (Check screenshot). There've been no configuration changes in between. I'm the only person configuring the Zoom app & Mattermost part.

![image](https://user-images.githubusercontent.com/9337414/106881611-0c4bd000-66de-11eb-9139-3d605218bde8.png)

The Zoom user exists and didn't change his password. As the error message point to an invalid token & no tokens were changed on the Mattermost & Zoom side, the question arises, why the token is suddenly invalid.

With INFO logging switched on in Mattermost the following line is logged:
![image](https://user-images.githubusercontent.com/9337414/106883298-18389180-66e0-11eb-8534-83fb0acb5abc.png)

Mattermost Zoom plugin config looks like this:
![image](https://user-images.githubusercontent.com/9337414/106882060-9a27bb00-66de-11eb-8755-c6ef0b74f2e6.png)

If I disconnect & reconnect to Zoom, I'm asked for a new authentication with my Zoom client. Afterwards, /zoom start, works again.
![image](https://user-images.githubusercontent.com/9337414/106884421-93e70e00-66e1-11eb-9176-d03b8c789941.png)

My understanding is, that with account based authentication, a user level authentication is not necessary.

Is this a bug or an error on my side. We used the user based authentication until the version supporting account based authentication was released & then created a new app on the Zoom marketplace.

Thanks

JP

**Comment by larkox** [comment]
Not sure how this could happen. How long would you say passed between you authorized mattermost the first time, until you got the invalid token problem? (a rough time frame is enough, like one day, a few days, one week, a few weeks...)

**Comment by jprusch** [comment]
It was working on Tuesday & stopped working today, so about 2 days.

**Comment by jprusch** [comment]
Happend again today after working on 2.5 days ago. Dis- & reconnecting to Zoom lets me start meetings again. But this is not the solution.

Mattermost log is clean, not logging any errors or warnings.

**Comment by larkox** [comment]
Thank you @jprusch. I will investigate this further.

**Comment by charlesogilvie** [comment]
At my company we are experiencing the same issue and resolved it the first time with /zoom disconnect and /zoom connect

Our connection from Mattermost to Zoom lasted an hour the first time. We are connected for the second time now.

Same error was displayed when trying to start a meeting:
Error fetching user: error fetching zoom user: Get "https://api.zoom.us/v2/users/fake@user.com": oauth2: cannot fetch token: 401 Unauthorized
Response: {"reason":"Invalid Token!","error":"invalid_request"}

No information in the Mattermost logs - Thank you

**Comment by larkox** [comment]
After looking deeper into this and the documentation, the first token received last for just one hour. A refresh has to be made in order to use the token.

**Comment by larkox** [comment]
To fix this, changes will be needed in the code. We hope to have this fixed this in the next release.
