### ISSUE TITLE
Zoom plugin - 1 MM install with 3 Zoom orgs/accounts

### ISSUE THREAD

**Issue by jcolinger3** [mattermost/mattermost-plugin-zoom#218]
Hello,

Our Mattermost CE is for our "school district" for 3 schools with Staff, and each school has their own Zoom account.

Is this plugin capable of handling the OAuth for the 3 distinct Zoom accounts that we have for each school?  It seems like it is just for one.

**Comment by raghavaggarwal2308** [comment]
@mickmister I think this can also be closed as a duplicate of #241
