### ISSUE TITLE
User can start meeting in a channel that they do not have appropriate permissions to post in

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/mattermost-plugin-zoom#223]
I don't know if this is necessarily a Zoom plugin issue, but since it was the Zoom plugin where I noticed it I thought I would start here and then if I need to open an issue in the main MM repo then I can do that or maybe it's just a config setting on our end.

We have a channel that we have effectively made read-only using [channel moderation](https://docs.mattermost.com/manage/team-channel-members.html#channel-moderation-e20) so that only channel admins can post. However, the other day someone who is **not** a channel admin was able to click the Zoom plugin button in the channel and it posted the "I have started a meeting" dialog to the channel. 

Is there a way to prevent this?

**Comment by maisnamrajusingh** [comment]
This is similar to the msteams issue, so will work on this once we resolve that one. https://github.com/mattermost/mattermost-plugin-msteams-meetings/issues/29
