### ISSUE TITLE
How to install Zoom plugin for mattermost

### ISSUE THREAD

**Issue by weilong0820** [mattermost/mattermost-plugin-zoom#225]
Hi, i dont know how to install zoom plugin, can you help me? Thanks!

**Comment by larkox** [comment]
You have all the needed information in the documentation of the plugin. In particular here:
https://mattermost.gitbook.io/plugin-zoom/installation/install-zoom-plugin

**Comment by weilong0820** [comment]
![image](https://user-images.githubusercontent.com/56424996/134757536-74ac627d-0a4b-420c-b9c2-a743abd69bf8.png)
![image](https://user-images.githubusercontent.com/56424996/134757547-7f62feb0-8323-45ef-927b-ed41eeced5aa.png)
But when i click connect Zoom account then 404 NOt Found

**Comment by larkox** [comment]
@weilong0820 Just to confirm, does the URL seems correct? (Is it missing any important information as might be the port).

Also, do you have correctly configured the Site URL in the system console?

**Comment by raghavaggarwal2308** [comment]
@mickmister The creator of this issue has not replied in 2 years and I don't think anyone else is facing this issue. Can we close this?

**Comment by mickmister** [comment]
@raghavaggarwal2308 Yes it seems there is likely some infrastructure issue here
