### ISSUE TITLE
Update mattermost-setup.md to remove references to "Enable Password Based Authentication"

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-zoom#229]
We used to have a setting that was called "Enable password based authentication". We removed that setting and we decide whether we want Password based authentication depending on whether OAuth is Enabled or not.

The scope of this ticket is to:
- Remove the reference in mattermost-setup.md and any other part of the documentation to the "Enable password based authentication" setting.
- Update screenshots to show the current look of the settings (without the "Enable password based authentication" setting).

Out of the scope:
- Add information about AccountLevelApp setting (this setting is also new, and will show in the screenshot, but we will cover it in a different Issue).

**Comment by joshalling** [comment]
I can take this one.

**Comment by larkox** [comment]
@joshalling All yours. Thanks!
