### ISSUE TITLE
Update tokens when they get refreshed on User Level OAuth

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-zoom#235]
Right now, on Account Level OAuth, OAuth tokens are updated when the token gets refreshed.

https://github.com/mattermost/mattermost-plugin-zoom/blob/2acac55e7fc60b0da7cb7f6c3ef17f33a844cd78/server/zoom/oauth.go#L101-L120

This should be also done for User Level Apps. Also, it would be nice to check if all paths are correctly updating all the tokens (User Level and Account Level).

**Comment by vicky-demansol** [comment]
`
 ​func​ (​c​ ​*​OAuthClient​) ​getUserViaOAuth​(​user​ ​*​model.​User​) (​*​User​, ​error​) { 
 ​        ​url​ ​:=​ ​fmt​.​Sprintf​(​"%s/users/me"​, ​c​.​apiURL​) 

 ​                ​currentToken​, ​err​ ​:=​ ​c​.​api​.​GetZoomSuperUserToken​() 
 ​                ​if​ ​err​ ​!=​ ​nil​ { 
 ​                        ​return​ ​nil​, ​errors​.​Wrap​(​err​, ​"error getting zoom super user token"​) 
 ​                } 

                ​tokenSource​ ​:=​ ​c​.​config​.​TokenSource​(​context​.​Background​(), ​currentToken​) 
 ​                ​updatedToken​, ​err​ ​:=​ ​tokenSource​.​Token​() 
 ​                ​if​ ​err​ ​!=​ ​nil​ { 
 ​                        ​return​ ​nil​, ​errors​.​Wrap​(​err​, ​"error getting token from token source"​) 
 ​                } 
  
 ​                ​if​ ​updatedToken​.​AccessToken​ ​!=​ ​currentToken​.​AccessToken​ { 
 ​                        ​kvErr​ ​:=​ ​c​.​api​.​SetZoomSuperUserToken​(​updatedToken​) 
 ​                        ​if​ ​kvErr​ ​!=​ ​nil​ { 
 ​                                ​return​ ​nil​, ​errors​.​Wrap​(​kvErr​, ​"error setting new token"​) 
 ​                        } 
 ​                } 
  
 ​                ​c​.​token​ ​=​ ​updatedToken
 ​        ​if​ ​c​.​isAccountLevel​ { 
 ​                ​url​ ​=​ ​fmt​.​Sprintf​(​"%s/users/%s"​, ​c​.​apiURL​, ​user​.​Email​)   
 ​
 ​        } 
 ...`

Is it good to update like that ? @larkox

**Comment by larkox** [comment]
This seems the functionality for the account level oauth, not for the user level oauth. Feel free to create a PR so we can look better at the changelog.

**Comment by raghavaggarwal2308** [comment]
@mickmister I think this issue has been fixed with PR #253. Can you please confirm that? If yes, can we close this issue?
