### ISSUE TITLE
After Executing The Zoom Command, Command is still there in the thread Chat (issue only generate in the Thread Chat)

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-plugin-zoom#238]
https://user-images.githubusercontent.com/89907719/141177129-4c16aba5-ef44-4f11-9626-9c41643227fa.mp4

**Comment by hanzei** [comment]
This is a not a zoom specific issue tracked in https://mattermost.atlassian.net/browse/MM-34521

**Comment by hanzei** [comment]
Good catch @dipak-demansol :+1:
