### ISSUE TITLE
Single Mattermost, three Zoom accounts

### ISSUE THREAD

**Issue by jcolinger3** [mattermost/mattermost-plugin-zoom#241]
Hello, we have a single Mattermost install.  But we have 3 different Zoom accounts (required for accounting, legal purposes).

Is there any method to use this plugin in our use case?
I've successfully used User Account oAuth to get it set up with one Zoom account/email domain.

But presumably, the other users that have an email that belongs to the other two Zoom accounts are failing to Authorize/Connect.  I assume because the ClientID/Secret are different and the email domains don't exist in the plugin configured ClientID/Secret Zoom App.

**Comment by jcolinger3** [comment]
Does anyone else have a set up like ours?  Not sure what to do, but we'd really like to get the Zoom integration working.

**Comment by larkox** [comment]
@aaronrothschild :point_up: 

As of today, there is no way in the plugin to support such a setup.

**Comment by raghavaggarwal2308** [comment]
> As of today, there is no way in the plugin to support such a setup.

@mickmister Can we close this issue as it is not possible?

**Comment by mickmister** [comment]
@raghavaggarwal2308 I think @larkox meant "it's currently not supported by the plugin". I think this would greatly increase the complexity of the plugin, so unfortunately I think we should close as a "Won't Do"

We can consider implementing if there is more traction on the issue. Closed issues are still visible for commenting, so I think closing and continuing to monitor will work. Apologies for this @jcolinger3, but we will not be implementing this at the moment.
