### ISSUE TITLE
Add auto complete for zoom topic command

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-zoom#244]
The functionality for this is looking good! 
One request would be, is it possible to also update the slash command auto complete functionality for start with help text such as **topic (optional)** This would help users discover the new functionality.

_Originally posted by @dipak-demansol in https://github.com/mattermost/mattermost-plugin-zoom/pull/209#pullrequestreview-802946381_

**Comment by hanzei** [comment]
cc @kott

**Comment by jeromegrosse** [comment]
On it! :)

**Comment by hanzei** [comment]
Awesome, thanks @jeromegrosse :tada:
