### ISSUE TITLE
The post content for Zoom is being duplicated

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#254]
When a post is being created for Zoom to join a meeting, the post is being duplicated. 
![image](https://user-images.githubusercontent.com/35588783/156040061-76a13c50-15ec-4a5a-a727-1ed47ad1e67f.png)

- This happens consistently on Community.
- This happens from the channel icon as well as the start slash command
- This happens from browser and desktop
- On a  `/cloud` server i have running I was **not** able to reproduce the issue with the marketplace release `v1.5.1`

Steps:
- Connect to Zoom and start a Zoom meeting.  
**Observed**: post is duplicated

**The post appears correct in the RHS**

**Comment by DHaussermann** [comment]
If it's relevant - When the webhook updates the post on meeting end, the timestamps are different as 1 is in UTC. 
![image](https://user-images.githubusercontent.com/35588783/156040840-b05cf615-1eb9-4695-88f4-99f79ac45bf3.png)

**Comment by catalintomai** [comment]
other potential plugins: jitsi, nps, playbooks(?), boards(?)

**Comment by hanzei** [comment]
![Screenshot from 2022-02-28 21-01-41](https://user-images.githubusercontent.com/16541325/156050601-dc29280a-0569-4a36-84ed-1cf8df4f5f03.png)

This issue also reproduces with Jitsi. @DHaussermann Please open a Jira ticket.

**Comment by hanzei** [comment]
Playbooks is also effected 
![Uploading Screenshot from 2022-03-01 11-03-46.png…]()

**Comment by larkox** [comment]
May be a change in webapp were it is showing both the attachment and the plugin custom post?

**Comment by hanzei** [comment]
@DHaussermann To ensure this doesn't get lost: Is there a ticket yet?

**Comment by raghavaggarwal2308** [comment]
@mickmister @DHaussermann This issue is not reproducible on our end. Can you please share the server version on which you facing it?
