### ISSUE TITLE
Use to CSRF Header or Form Field

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-zoom#26]
On MM `master` pressing the start meeting button throws an error in the system log:
`CSRF Check failed for request - Please migrate your plugin to either send a CSRF Header or Form Field, XMLHttpRequest is deprecated`

**Comment by jasonblais** [comment]
@hanzei Possibly related to https://mattermost.atlassian.net/browse/MM-15783

**Comment by crspeller** [comment]
Those changes should help. But the zoom plugin still needs to use `Client4.getOptions` like other plugins do.

**Comment by levb** [comment]
@crspeller can you please provide a link to an example?

**Comment by crspeller** [comment]
Jira plugin: https://github.com/mattermost/mattermost-plugin-jira/blob/512408ed5cab1238ebe4b718f2120047384d5ac0/webapp/src/client/index.js#L14

**Comment by bolariin** [comment]
I think #51 might have resolved this issue

**Comment by jasonblais** [comment]
> I think #51 might have resolved this issue

Pinging @mickmister and @crspeller to confirm after the holidays

**Comment by crspeller** [comment]
Confirmed. Fixed by #51
