### ISSUE TITLE
Error installing v1.6.0 from marketplace: "Unable to verify plugin signature"

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#266]
For reasons unknown at the moment, the marketplace PR https://github.com/mattermost/mattermost-marketplace/pull/287 results in the Zoom plugin failing to install via the marketplace. I receive the following error:

![image](https://user-images.githubusercontent.com/6913320/172527045-99658cf8-82cd-47fe-8347-f9f49bb11d33.png)

**Comment by agarciamontoro** [comment]
I bet that the signature in the manifest is the one from v1.5.1. I'll take a look

**Comment by agarciamontoro** [comment]
Ah, you already did, thank you!
