### ISSUE TITLE
Does Zoom app need to be published on Marketplace?

### ISSUE THREAD

**Issue by akuzia** [mattermost/mattermost-plugin-zoom#290]
There are some misconceptions about user level app. After creating one anyone that has no access to account created the application has the "[Application not found error](https://i.imgur.com/4yWEnAP.png)". Is it mandatory to have Zoom OAuth application published on Zoom Marketplace?

**Comment by mickmister** [comment]
Hi @akuzia, thanks for creating this issue. What is your use case for running this plugin? Typically, it's used inside of an organization where each user is associated with the given organization. I'm not sure if that is a requirement, but that is how it's usually used.

It's possible that the Zoom app needs to be published to the marketplace if your users are outside of the account/organization. Can you please provide more info about your situation? Thank you

**Comment by akuzia** [comment]
We run Mattermost instance as a Q/A for our users, sometimes there is a need to create Zoom meetings. We prevously used Slack with its Zoom integration and wanted to mimic its workflow on Mattermost. Thanks for your suggestion, I will take a look on organization management. Maybe we can get around with only subset of users creating meetings
