### ISSUE TITLE
Investigate whether webhook verification should be used on `deauthorize` route

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#291]
For the `deauthorize` feature, we are checking the legacy webhook secret, but not performing the newer webhook verification.

The task here is to investigate the `deauthorize` call, to see if the Zoom webhook verification information is in the HTTP headers. See https://github.com/mattermost/mattermost-plugin-zoom/pull/279 for more details on the webhook verification requirements.

https://github.com/mattermost/mattermost-plugin-zoom/blob/229517fa473f58f0792ea6ef735ea0b2c838359e/docs/installation/zoom-configuration/zoom-setup-oauth.md#L44-L53

_Originally posted by @mickmister in https://github.com/mattermost/mattermost-plugin-zoom/pull/279#discussion_r1132825590_

**Comment by mickmister** [comment]
@raghavaggarwal2308 I'm thinking we should just not worry about this. We already have our own mechanism (our webhook secret) to determine the validity of the request.

**Comment by mkdbns** [comment]
Thanks for the feedback @mickmister . Will you close this issue then?
