### ISSUE TITLE
Admin Guide - Installation sites are offline

### ISSUE THREAD

**Issue by govbetrieb** [mattermost/mattermost-plugin-zoom#303]
Hi, under:

 -Admin guide
--Installation

all sites from mattermost.gitbook.io are down.
For example this ones:

[Zoom setup (User Level App)](https://mattermost.gitbook.io/plugin-zoom/v/release_v1.5.1-cloud/installation/zoom-configuration/zoom-setup-user-level-app)

[Zoom setup (Account Level App)](https://mattermost.gitbook.io/plugin-zoom/v/release_v1.5.1-cloud/installation/zoom-configuration/zoom-setup-oauth)

[Webhook configuration](https://mattermost.gitbook.io/plugin-zoom/v/release_v1.5.1-cloud/installation/zoom-configuration/webhook-configuration)

[Configure Mattermost for the Zoom plugin](https://mattermost.gitbook.io/plugin-zoom/v/release_v1.5.1-cloud/installation/mattermost-setup)

**Comment by cwarnermm** [comment]
Fixed via https://github.com/mattermost/mattermost-plugin-zoom/pull/320

**Comment by raghavaggarwal2308** [comment]
@mickmister Can we close this issue as fixed?
