### ISSUE TITLE
Add `/zoom start` command

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-zoom#31]
Mobile plugins are currently not supported. As a workaround a slash command `/zoom start` should be implemented, that starts a zoom call in the current channel.

Follow up from https://community.mattermost.com/core/pl/qy7bidcuhbgt3xu7rprg6h697c

cc @aaronrothschild

**Comment by dhadiseputro** [comment]
Is this workaround going to be mobile-device-specific then? Or basically make `/zoom start` command to do the same thing as clicking on the video recording icon on the header?

**Comment by aaronrothschild** [comment]
@dhadiseputro I think that doing the same thing as clicking on the "Zoom" button on the channel header bar would be perfect.  It's also been a request from others, when they don't realize that the zoom button is actually there... they just start typing `/zoom...` People have reported to me their expectation for a slash command a couple of times anecdotally.

**Comment by dhadiseputro** [comment]
I am new to mattermost development. Based on reading other plugin repos, do I start by creating the file server/command.go to add the `/zoom start` command?

**Comment by hanzei** [comment]
@dhadiseputro That is correct. Let me know, if you need more guidance.

**Comment by dhadiseputro** [comment]
I'll work on this.

So my idea is to add `command.go` file in server/. Then inside add the `ExecuteCommand` function that will have a switch case for different commands (right now we only have 1 command `/zoom` and action is `start`). 
Inside the `start` case, I will do something similar to `handleStartMeeting` in http.go. High level idea is like this:
- Create `zoom.Meeting` instance with correct data.
- Invoke `p.zoomClient.CreateMeeting` with the meeting instance.
- Create a post with the meeting info and post it to the channelId.

This sounds good?

Anyways, I am not really sure on how to test the functionality after I am done. How do I create a build with my code and test my feature? Fyi, I am running on a mac.

**Comment by dhadiseputro** [comment]
I have a question, how can I differentiate between a user invoking `/zoom start` from a private message (DM) or a channel?

**Comment by hanzei** [comment]
The [`CommandArgs`](https://godoc.org/github.com/mattermost/mattermost-server/model#CommandArgs) struct contains a `TeamId` field that is empty if and only if the channel is a DM.

**Comment by hanzei** [comment]
For deploying your build you can follow the steps outlined at https://github.com/mattermost/mattermost-plugin-starter-template#getting-started

**Comment by dhadiseputro** [comment]
Okay thanks, I'll check it out! 
I am trying to understand how the main mattermost server is connected to the different plugins (or how the mattermost-server knows to include the zoom plugin during build). Is it through the `Makefile` in mattermost-server repo?

**Comment by hanzei** [comment]
The makefile in this repo uploads the bundle to the MM server. This is done with this https://github.com/mattermost/mattermost-plugin-zoom/blob/master/Makefile#L126 line in `Makefile`.

**Comment by dhadiseputro** [comment]
just want to make sure, I only need to add command.go right? I tried to `make run` in mattermost-server/ then `make deploy` in mattermost-plugin-zoom/ but I can't get `/zoom` on the localhost. 

I am guessing that I am missing this part:
```You will need to restart your server and manually enable your plugin.```
I am not sure what to do here.

**Comment by dhadiseputro** [comment]
I have tried a lot of things (to deploy my build) with no success. :(
I go this error when doing `make deploy`:
```
...
plugin built at: dist/zoom-1.0.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
DEBU[2019-08-12T22:41:21.133161-07:00] POST - /api/v4/users/login                    caller="web/handlers.go:58"
ERRO[2019-08-12T22:41:21.153273-07:00] Enter a valid email or username and/or password.  caller="mlog/log.go:172" err_details= err_where=login http_code=401 ip_addr="::1" method=POST path=/api/v4/users/login request_id=o55k6xid37bbfegqkco56yhq5r user_id=
```
Is the above saying that it can't find the `MM_ADMIN_USERNAME`/`MM_ADMIN_PASSWORD` env var?

**Comment by hanzei** [comment]
Yes, that means the of `MM_ADMIN_USERNAME` and `MM_ADMIN_PASSWORD` is either wrong or not found.

**Comment by dhadiseputro** [comment]
What about this? https://github.com/mattermost/mattermost-plugin-zoom/issues/31#issuecomment-520692246

**Comment by hanzei** [comment]
If `make deploy` doesn't work for what ever reason you can upload the plugin manually:
1. Start your local mattermost server by running `make run` inside your server directory
2. Build the plugin bundle by running `make dist`
3. Go to http://localhost:8065/admin_console/plugins/management
4. Upload your bundle
5. Enable the plugin

Let me know, you need additional help.

**Comment by dhadiseputro** [comment]
Thanks! That helped a lot!
So I added `RegisterCommands` in plugin.go, when I try to do `make` it raised a panic.
```
panic: 
assert: mock: I don't know what to return because the method call was unexpected.
	Either do Mock.On("RegisterCommand").Return(...) first, or remove the RegisterCommand() call.
	This method was unexpected:
		RegisterCommand(*model.Command)
		0: &model.Command{Id:"", Token:"", CreateAt:0, UpdateAt:0, DeleteAt:0, CreatorId:"", TeamId:"", Trigger:"zoom", Method:"", Username:"", IconURL:"", AutoComplete:true, AutoCompleteDesc:"Available commands: start", AutoCompleteHint:"[command]", DisplayName:"Zoom", Description:"Integration with Zoom.", URL:""}
	at: [api.go:2137 plugin.go:63 plugin_test.go:139]
```
Based on the logs, I am assuming that it is using mock. How can I modify the mock to add `RegisterCommand`? thanks!

**Comment by hanzei** [comment]
`make' also runs the tests. For now it's suitable to just compile the bundle with `make dist` and ignore the tests for now.

You can fix them by mocking the api call with `				api.On("RegisterCommand", mock.AnythingOfType("*model.Command")).Return(nil)`

**Comment by dhadiseputro** [comment]
Alright! I can get it to work! One thing I am confused with, I am in a personal message room with myself and typed in `/zoom start`. This goes to the case where `if args.TeamId != ""`. I thought DM have `TeamId == ""`?

**Comment by hanzei** [comment]
I thought the same. But after checking the behaviour again I can confirm that `args.TeamId` is set when the command is triggered from a DM. Sorry for the confusion.

You can check the channel type by fetching the channel via https://developers.mattermost.com/extend/plugins/server/reference/#API.GetChannel

**Comment by dhadiseputro** [comment]
Thanks! That did the work. I am able to get it working, but I can't test the part to create the meeting room (since I don't have a zoom plan that supports REST API) aside from following the exact code used in http.go. The workflow I have stopped at the point where we are obtaining the zoom user using `zoomClient`. 
Can I create a PR and ask for one of you guys to test it using a paid zoom plan you have?

**Comment by dhadiseputro** [comment]
oh wow, interestingly I can the zoom to work with my free zoom plan! 
After I typed in `/zoom start`:
![image](https://user-images.githubusercontent.com/22417762/63219491-d4d31780-c127-11e9-8be8-0164518ba096.png)

**Comment by hanzei** [comment]
Awesome :tada: Looking forward to your PR

**Comment by aaronrothschild** [comment]
Great work @dhadiseputro !  Glad to see you could get it working.  This will be handy!
