### ISSUE TITLE
Not able to create new meeting in the threads view after clicking "Create New Meeting" button

### ISSUE THREAD

**Issue by raghavaggarwal2308** [mattermost/mattermost-plugin-zoom#317]
#### Summary
Not able to create a new meeting in the threads view after clicking the "Create New Meeting" button.

#### Steps to reproduce:
1. Have CRT (Collapsed Reply Threads) enabled, and open the Threads view.
2. Open a thread that pops into the RHS.
3. Start a new meeting by clicking the Zoom button on the right.
2. Without ending the meeting started, try to start a new meeting again.
3. Click on the "Create New Meeting" button.

#### Expected behavior:
- The user should be able to start a new meeting.

#### Current behaviour:
- No new meeting is posted inside the channel.

**Comment by mickmister** [comment]
@raghavaggarwal2308 Is this the case only for threads view?

**Comment by raghavaggarwal2308** [comment]
@mickmister It was occurring for channels as well but that was because of a different reason and that has been fixed [here](https://github.com/mattermost/mattermost-plugin-zoom/pull/316). But we still need to debug and fix the issue in the threads view.

**Comment by mickmister** [comment]
@raghavaggarwal2308 I'm wondering if this is really a "bug" though. Maybe I don't fully understand the issue, but why would someone want to have two meetings open? What happens to the first meeting? I suppose maybe the user would want to "abandon" the "created" meeting because no one joined it, and thus it's not really a "meeting"?

**Comment by raghavaggarwal2308** [comment]
@mickmister The current flow in a channel is that if a user tries to start a new meeting without ending the previous meeting created by him, he gets an option to join the existing meeting or create a new meeting. The previous meeting will still be valid but Zoom allows a user to join a single meeting at a time.
![image](https://github.com/mattermost/mattermost-plugin-zoom/assets/55234496/4c1593d2-7c2d-4224-8fb9-b82ea9cc0e5d)

But the current flow in thread view is that if a user tries to start a new meeting without ending the previous one, he gets an option to create a new meeting but on clicking that button nothing happens.
