### ISSUE TITLE
Error when PMI user preference is set to "ask", and attempt to start meeting

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#338]
When attempting to start a meeting with the PMI preference set to "ask", I see this `Unexpected end of JSON input` ephemeral message error below.

Unfortunately, I'm not able to get any more context on why this is happening. There is nothing in the logs related to this error occurring. The error occurs after clicking the zoom icon in the Apps bar on the right side of the screen, before clicking "USE PERSONAL MEETING ID" etc.

<img width="680" alt="CleanShot 2024-01-17 at 15 43 36@2x" src="https://github.com/mattermost/mattermost-plugin-zoom/assets/6913320/20b0ae30-b193-4227-832a-260c67f644ee">

**Comment by raghavaggarwal2308** [comment]
@mickmister Can we close this issue? As this is already fixed in release 1.7.0.
