### ISSUE TITLE
Zoom setup instructions don't match the current process in Zoom marketplace

### ISSUE THREAD

**Issue by cmseal** [mattermost/mattermost-plugin-zoom#351]
"In the top left select Develop and then Build App."

The Develop menu appears top right, and "Build App" appears to be a new workflow, vs the option of "Build Legacy App", which appears to more closely match some of the screenshots in the rest of the guide. (note; "Build App" is unavailable as the screenshot was with a non-admin user).

<img width="292" alt="Screenshot 2024-03-27 at 12 42 50" src="https://github.com/mattermost/mattermost-plugin-zoom/assets/24206640/365c4c85-99bd-4655-b118-6aaa99bc4a0a">

"Select Scopes and add the following scopes: meeting:read, meeting:write, user:read."

Regardless of choosing "Build Legacy App", the Scopes section now shows dozens of granular scope permissions rather than wider ones suggested.  Selecting them all from "meeting:read", "meeting:write" and "user:read" isn't possible as the limit is 50 and there are more than this in total.

<img width="732" alt="Screenshot 2024-03-27 at 12 42 24" src="https://github.com/mattermost/mattermost-plugin-zoom/assets/24206640/86fdca0e-a4d0-4420-91f8-4f91d5eb0ae0">

**Comment by mickmister** [comment]
Hi @cmseal, thanks for filing this issue. We are working on this now and will have more info shortly :+1:
