### ISSUE TITLE
Settings command not available and unable to set/have unique ID meetings

### ISSUE THREAD

**Issue by cmseal** [mattermost/mattermost-plugin-zoom#354]
The `/zoom settings` command is not possible (possibly due to account-level OAuth).  Likewise meaning that only personal "per user" meeting IDs are used each time.

Is there a setting or permission required to allow unique meetings each time? likewise, do they persist or expire after a period of time?

<img width="384" alt="Screenshot 2024-04-03 at 15 37 40" src="https://github.com/mattermost/mattermost-plugin-zoom/assets/24206640/630d9ae3-a1e1-4573-9f06-8bb162df03fc">

<img width="338" alt="Screenshot 2024-04-03 at 15 38 24" src="https://github.com/mattermost/mattermost-plugin-zoom/assets/24206640/17df4b97-3e1e-4884-b5e5-718c052b9165">

**Comment by cmseal** [comment]
Hi @ayusht2810

Per my first screenshot, when I try to run `/zoom settings`, it just tells me which commands are available (start, connect, disconnect), so it behaves as if it's not even a valid command.

MM server is v9.5.3 and Zoom plugin is v1.6.2

If you require any further information, please do let me know.  I was wondering if it was permissions scope related with the Zoom OAuth setup, but we've got the scopes for account-level as per the recent update to the README.

**Comment by ayusht2810** [comment]
@cmseal The plugin `v1.6.2` does not support the `/zoom settings` command. The command was introduced in the latest release https://github.com/mattermost/mattermost-plugin-zoom/releases/tag/v1.7.0. If you want to have that functionality working, you need to update the plugin version to `v1.7.0`. Please let me know if you have any other concerns regarding this.

**Comment by cmseal** [comment]
@ayusht2810 Thanks for clarifying - we're using the version that the MM app marketplace recommends, which is 1.6.2 and doesn't suggest or notify there's a newer version available.

**Comment by ayusht2810** [comment]
@cmseal Thanks for understanding. We are already working on releasing the new version for the plugin on marketplace.
