### ISSUE TITLE
New webhooks don't work? (Post in Mattermost is not modified after meeting ends)

### ISSUE THREAD

**Issue by Amonith** [mattermost/mattermost-plugin-zoom#37]
Now tracked in https://mattermost.atlassian.net/browse/MM-19288

Hi,

About a year ago when we tested this plugin in our company, meeting post messages were correctly modified when meeting ended etc.
Currently though nothing happens, only the starting message is posted.

I think that it is related to this check:

https://github.com/mattermost/mattermost-plugin-zoom/blob/93b4a61313209536ac4a377092a6fd8227c79791/server/http.go#L64

Currently Zoom posts this to the webhook:

```
"requestBody": {
    "event": "meeting.ended",
    "payload": {
        "account_id": "XXXXX",
        "object": {
            "duration": 0,
            "start_time": "2019-08-22T08:21:56Z",
            "timezone": "Europe/Warsaw",
            "topic": "XXXX's Personal Meeting Room",
            "id": "XXXX",
            "type": 4,
            "uuid": "XXX",
            "host_id": "XXXXX"
        }
    }
},
```

There is no status here. Am I missing something?

**Comment by Amonith** [comment]
I can fix this if you confirm that it is a bug.

**Comment by aaronrothschild** [comment]
This just worked on our instance:
![image](https://user-images.githubusercontent.com/915956/63526356-24ad3800-c4b4-11e9-8ba3-303616bebd07.png)

**Comment by Amonith** [comment]
How does your setup look like on the Zoom side?
We have the JWT app for the basic thing as mentioned in the documentation:

https://docs.mattermost.com/integrations/zoom.html

And the Webhook-only app for webhooks, which posts stuff about meetings to:

https://OUR_INSTANCE/plugins/zoom/webhook?secret=XXX

We are not using the paid API of Zoom, just those webhooks and JWT app.
Maybe in your company you have some kind of legacy Zoom config which they are still supporting, but it is not possible to create new apps with this config?

**Comment by aaronrothschild** [comment]
@Amonith Sorry for the late reply, I've updated the documentation that states that the Zoom plugin doesn't work with unpaid Zoom accounts.   We do support having a mix of free/paid accounts, but you'll need at least one paid account to use the Zoom plugin I believe.

https://github.com/mattermost/docs/pull/3068

**Comment by Amonith** [comment]
Hi @aaronrothschild,
We do have one paid account and the JWT app is configured on that account properly (as described in the documentation). I still am confused, because Zoom does send all relevant events to MM, but they look different to what the code expects.

**Comment by levb** [comment]
Should've been fixed by https://github.com/mattermost/mattermost-plugin-zoom/pull/47
