### ISSUE TITLE
The already started meeting is not aware of if the meeting stared in the last 30 seconds has ended 

### ISSUE THREAD

**Issue by raghavaggarwal2308** [mattermost/mattermost-plugin-zoom#373]
More information here:
https://community.mattermost.com/core/pl/xh1k4upb6ff8jni8cuzeyw9wqy

Steps to reproduce:
1. Start a zoom meeting in a channel.
2. End the above meeting and try to start a new meeting within 30 seconds.

Expected behavior:
A new meeting is started

Current behaviour:
Getting a post with the message that a meeting was recently created in the channel.

**Comment by Kshitij-Katiyar** [comment]
@mickmister @wiggin77 
when a `meeting-ended` notification is received from the webhook, we [update](https://github.com/mattermost/mattermost-plugin-zoom/blob/master/server/webhook.go#L116)  the post's `meeting_status` prop.
If we add the following check in the [checkPreviousMessage](https://github.com/mattermost/mattermost-plugin-zoom/blob/5500184f26b5b64ca859503ad8eba4de44bbee15/server/http.go#L727) function, we can resolve this issue.

```
meetingStatus := getString("meeting_status", post.Props)
if meetingStatus == zoom.WebhookStatusEnded {
    continue
}
```
However, this fix has one limitation: it will only work if the user has successfully set up the webhook.

Is this approach fine? Should we go ahead and implement this?

**Comment by mickmister** [comment]
> However, this fix has one limitation: it will only work if the user has successfully set up the webhook.

@Kshitij-Katiyar The core feature depends on the webhook anyway right? Sounds good to me :+1:
