### ISSUE TITLE
Testing workflow for adding new issues to Github board automatically

### ISSUE THREAD

**Issue by raghavaggarwal2308** [mattermost/mattermost-plugin-zoom#394]
Workflow PR:
https://github.com/mattermost/mattermost-plugin-zoom/pull/387

Github board:
https://github.com/orgs/mattermost/projects/9/views/1

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Looks like [the workflow](https://github.com/mattermost/mattermost-plugin-zoom/actions/runs/10280764398/job/28448845869) is not working because of some missing keys. We are using some secrets and vars int he CI, I think there are not present in Zoom plugin. Are you able to add the same to the repo, I think @mickmister must have added them to the Github plugin repo.

**Comment by wiggin77** [comment]
> @wiggin77 Looks like [the workflow](https://github.com/mattermost/mattermost-plugin-zoom/actions/runs/10280764398/job/28448845869) is not working because of some missing keys. We are using some secrets and vars int he CI, I think there are not present in Zoom plugin. Are you able to add the same to the repo, I think @mickmister must have added them to the Github plugin repo.

Which secrets specifically are needed?  I don't has admin access to the repo, but I can ask someone to add them.

**Comment by raghavaggarwal2308** [comment]
@wiggin77 The below screenshot contains the required secrets/vars
![image](https://github.com/user-attachments/assets/f8a8db41-30a5-42d5-9481-11941555299d)

**Comment by wiggin77** [comment]
> @wiggin77 The below screenshot contains the required secrets/vars ![image](https://private-user-images.githubusercontent.com/55234496/356134187-f8a8db41-30a5-42d5-9481-11941555299d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMTE0NzIsIm5iZiI6MTcyMzMxMTE3MiwicGF0aCI6Ii81NTIzNDQ5Ni8zNTYxMzQxODctZjhhOGRiNDEtMzBhNS00MmQ1LTk0ODEtMTE5NDE1NTUyOTlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDE3MzI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YjQyOWIzYjdjMTk1OGE4Njc4NDVjNWVlN2E1ZDQ0ZDZhYzE5NmU1Y2FhYjg3YThjYzhmNjU2YjUxOWY1M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nC3--EuM1FZmrXKiYNpAEvRnxbSQ9-v_pe16NdeXX48)

I have requested these secrets be added by our Delivery team.

**Comment by saturninoabril** [comment]
Should be good now.

**Comment by raghavaggarwal2308** [comment]
@saturninoabril @wiggin77 Working now, thanks!
