### ISSUE TITLE
implement /zoom connect with OAuth

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-zoom#42]
Presently, the zoom plugin uses email addresses to connect user accounts.

An alternate way would be to implement a `/zoom connect` command, similar to that of the [Jira](https://github.com/mattermost/mattermost-plugin-jira) or [GitHub](https://github.com/mattermost/mattermost-plugin-github) plugins, using OAuth. The user mapping can then be stored in the KV store, following the above examples.

**Comment by levb** [comment]
Should also solve https://mattermost.atlassian.net/browse/MM-18828

**Comment by gopheros** [comment]
@levb I am starting to work on this issue as it is`Up For Grabs`.
What is a great channel to communicate the progress

**Comment by levb** [comment]
@gopheros Thank you for taking this on! Please feel free to join the conversation, and seek any advise/info you may need at https://community-daily.mattermost.com/core/channels/plugin-zoom.

**Comment by cpurta** [comment]
@levb I would like to take this one on and have already started working on implementing this.

**Comment by avddvd** [comment]
@levb @cpurta I was working on this and got the OAuth part working. I can collaborate with @cpurta here or can take another one
