### ISSUE TITLE
Zoom error: User not found on this account – in any configuration

### ISSUE THREAD

**Issue by cadavre** [mattermost/mattermost-plugin-zoom#43]
Hi, I followed the step-by-step described in Mattermost documentation. I have a 'Pro' account, created an Zoom app, copy-paste API key and secret. Applied to Mattermost.

Now when trying to start a meeting with Zoom all of our users are getting:
```
Zoom error: User not found on this account
```

User trying to start a new meeting has his own Zoom account. I tried to add users into Zoom > Admin > Users but that doesn't change much.

Most of our users are having Zoom.us accounts created with "Signup with Google".

Any ideas?

**Comment by levb** [comment]
@cadavre The Mattermost Zoom plugin currently identifies Zoom users by matching the emails on the Mattermost and Zoom accounts. Please make sure you have the same email addresses set up on both sides, and let us know if it does not work.

We have https://github.com/mattermost/mattermost-plugin-zoom/issues/42 to implement OAuth-based user mapping, but there is no specific timeline to implement it, yet.

**Comment by cadavre** [comment]
Yes, the email address for Mattermost user and Zoom.us account is the same. Double checked, also with non-Google account.

**Comment by cpoile** [comment]
@cadavre This looks like there's a problem with the API key setup. I know it's a bit of a pain, but could you go through the setup instructions (https://docs.mattermost.com/integrations/zoom.html) really carefully to make sure you've set up the zoom side of things correctly, and put the correct Zoom URL, Zoom API URL, Key, and Secret into the Mattermost Zoom settings?

Also, could you confirm the mattermost server version you're using, and the zoom plugin version?

If you're able to confirm that everything is set up correctly, we'll have narrowed down the possibilities a bit and we'll try next steps.

Thanks!

**Comment by cadavre** [comment]
Yes, I've actually made it twice this way.

I'm using Zoom's SaaS so URL and API URL are left empty.

I just don't quite get what's "Webhook Secret" for? Below I can see
> Use this webhook URL to set up the Zoom plugin. See documentation to learn more. https://SITEURL/plugins/zoom/webhook?secret=WEBHOOKSECRET

But there's nothing about it in "documentation" and also going to https://example.com/plugins/zoom/webhook?secret={generated_token} gives plain/text "Not authorized".

**Comment by cpoile** [comment]
@cadavre Good find -- I didn't realize the documentation didn't cover the webhook setup. I've filed a ticket for that: https://mattermost.atlassian.net/browse/MM-19364

But that won't affect your users not being found in Zoom by their email. That's an error that Zoom is sending back to Mattermost when it tries to start a meeting. 

Is there any other text that is displayed? There should be something like "We could not verify your Mattermost account in Zoom...". Maybe open up the browser's dev tools console before you click the zoom button, and then take a screenshot of what it shows in the console too, if there's anything there. 

Just trying to narrow down where the error is happening. 
Thanks!

**Comment by cadavre** [comment]
Thanks @cpoile for your response. I had chance to review the situation and I think all that is necessary is actually a docs update. There are few things:

1. On zoom.us, **even if you don't have** a "Pro, Business, Education, or API Zoom plan" – you can create now an integration application on zoom.us, so you can get API key and secret. I managed to get one with "Basic" account.

2. There is no mention about it, but **it is required by zoom.us API** now to have all people invited into master-account as "Users". It's not enough just to have zoom.us account with same email address as set in Mattermost.

3. Even if you can now create an API credentials with "Basic" account **and** users invited to your zoom.us master-account – you need "Pro, Business, Education, or API Zoom plan" to make use of Mattermost Zoom plugin.

Hope it's clear enough. :)

**Comment by larkox** [comment]
@cadavre Do you think this issue can be closed? You can take a look to the new documentation here:
https://app.gitbook.com/@mattermost/s/plugin-zoom/

**Comment by larkox** [comment]
The changes on the documentation and latest versions should have fixed these issues. Due to this and the inactivity of the thread, I am closing it.
@cadavre if you are still seeing any issues, feel free to reopen the thread.
