### ISSUE TITLE
Display username that created zoom chat

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-zoom#48]
#### Summary

Currently, the post made by the Zoom plugin shows the meeting ID, but does not show who created the meeting. When two people have created a meeting it is not obvious who created which meeting.

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/67719694-ac2d9080-f9a8-11e9-9831-21469414f5e0.png)

**Comment by ivernus** [comment]
Does this look like a possible solution @mickmister ? https://github.com/ivernus/mattermost-plugin-zoom/blob/master/webapp/src/components/post_type_zoom/post_type_zoom.jsx
