### ISSUE TITLE
Avoid race condition with users rapid-firing invites

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-zoom#54]
It happens often that 2 people are chatting in a channel, and one says, "let's zoom,"  both click the zoom link, and 2 meetings are started/opened.

It would be great if the plugin looked at the last few messages in the channel, and avoided starting a duplicate message. It could respond with an ephemeral message, "Another Zoom meeting <link> was just started X minutes ago in this channel, are you sure? <Yes, start> <No, cancel>"

**Comment by larkox** [comment]
May I take this one?

**Comment by levb** [comment]
@larkox Thank you!
