### ISSUE TITLE
Improve UX for linking Zoom Account 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#56]
Currently when new users launch a Zoom meeting for the 1st time they see a Zoom error with a link they must click.

![ZoomUserMapping](https://user-images.githubusercontent.com/35588783/71008114-18c63100-20b6-11ea-9d06-a0904eb9cca6.png)

As this is a path all users will hit, we should improve the UX to not make it look like an Error has occurred. Possibly a slightly different message with a button.

**Comment by levb** [comment]
We should return a regular response (*model.Response) from the command, not an error (*model.AppError) one in the case.

**Comment by larkox** [comment]
May I take this one?

**Comment by hanzei** [comment]
You are a breast, thanks @larkox :tada:

**Comment by larkox** [comment]
I just realised that due to recent changes on zoom to rollback the oauth, this is no longer in place. Should I make the changes on certain branch, should I wait for those changes to be reintegrated in the plugin, or should we close this issue?

**Comment by levb** [comment]
cc @jfrerich ^^ did we lose it?

**Comment by jfrerich** [comment]
@levb, yes, that was part of the oauth commit that was reverted.

Here is the text defined
https://github.com/mattermost/mattermost-plugin-zoom/blob/fb0d6e8fa6cae69ae1cd47b0277eb2c19589b0eb/server/plugin.go#L36

Here is where the text was getting used in the commit.
https://github.com/mattermost/mattermost-plugin-zoom/commit/dbf5eb9880d049f790a658f7fe6559427671a7cc#diff-7e42e9629fece6c3b56011e7de76423bL225

**Comment by hanzei** [comment]
@larkox Are you continuing to work on this or would we make this available for the public?

**Comment by larkox** [comment]
This PR covers this along with recovering the OAuth. Here is the link:
https://github.com/mattermost/mattermost-plugin-zoom/pull/78
