### ISSUE TITLE
Documentation or my plugin out of date?

### ISSUE THREAD

**Issue by zell-mbc** [mattermost/mattermost-plugin-zoom#64]
I am stuck at the stage where I am suppossed to copy the Client ID/Secret because my plugin does not show the OAuth section?
There is no enable OAuth toggle and no fields to enter the information below:
- Paste the Client ID and Client Secret into the fields in the System Console, and hit Save.
- Generate an Encryption Key to save the encryped tokens.

I am running Mattermost Team Edition Version: 5.19.0

**Comment by levb** [comment]
@zell-mbc the updated plugin is (or will be available shortly) via the Plugin Marketplace, use the menu in the top left corner to access it.

**Comment by zell-mbc** [comment]
Looks like I am running v 1.1.2 which is the same as on the marketplace. I will check again in the next couple of days.

Thanks for getting back!
