### ISSUE TITLE
Invalid meeting ID. (-1)

### ISSUE THREAD

**Issue by azkore** [mattermost/mattermost-plugin-zoom#71]
Mattermost server version: 5.19.1, team edition, installed in kubernetes via helm chart (https://github.com/mattermost/mattermost-helm/tree/master/charts/mattermost-team-edition)

Zoom plugin version: 1.3.0

Each time when I try to start a meeting Zoom Bot creates a link with the description "Zoom Meeting
Personal Meeting ID (PMI) : 0", which is opened at 'https://zoom.us/j/0' and Zoom shows the error messages 'Invalid meeting ID. (-1)'.

The user has the same email address as in Zoom and is added to the admin's Zoom account.
How can I debug it, are there any plugin specific logs to check?

**Comment by azkore** [comment]
I solved it by switch the checkbox 'Use this ID for instant meetings' to on in the Zoom account settings (it was off by default). Probably it would be good to add a note about it in the plugin description.

Otherwise this issue could be closed.

**Comment by drKreso** [comment]
<img width="852" alt="Screenshot 2020-05-07 at 13 39 42" src="https://user-images.githubusercontent.com/32063/81290360-39445700-9068-11ea-93de-06eba36d3050.png">

Just to clarify this is on https://zoom.us/profile
