### ISSUE TITLE
Webhooks not updating meeting info box

### ISSUE THREAD

**Issue by theopen-institute** [mattermost/mattermost-plugin-zoom#72]
Plugin version: 1.3
Mattermost version: 5.20.1

Related to:
https://github.com/mattermost/mattermost-plugin-zoom/issues/37

At present, the plugin does not seem to update meeting info boxes in response to webhook calls by Zoom. I can confirm that the webhook calls are being made by Zoom because the request is being received reliably by a webhook testing URL. I can also confirm that the webhook address entered in the jwt app configuration is correctly configured with the appropriate secret because that URL returns an empty response when requested in curl.

Any thoughts or suggestions? I'm happy to do more debugging, but I don't know quite where to start.

**Comment by levb** [comment]
Same as https://mattermost.atlassian.net/browse/MM-20656?

**Comment by hanzei** [comment]
@jfrerich assigning you to this one as you are assigned to the JIRA

**Comment by ThiefMaster** [comment]
I think this happens because Zoom sends a JSON payload, but the plugin tries to parse formdata.
