### ISSUE TITLE
Meeting creation collision post does not show the username

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-zoom#76]
A feature was added such that Zoom will show the username of the user who created the meeting. `sysadmin has started a meeting`
This feature does not work with the collision detection feature. When Zoom shows the other type of post warning a user that a meeting has already been started in the channel, the name shows as `undefined`
![ZoomCollisionUser](https://user-images.githubusercontent.com/35588783/76135777-41483200-5ff8-11ea-98fb-dccf3f39d2bc.PNG)

Steps:
- Start a meeting
- Note that the post shows your username as the creator
- Within 30 seconds start a 2nd meeting
**Expected**: Post shows `<your username> already created a zoom call recently`
**Observed**" Post shows `undefined already created a zoom call recently`

**Comment by larkox** [comment]
This PR waiting for review already solves this: https://github.com/mattermost/mattermost-plugin-zoom/pull/73/files

**Comment by DHaussermann** [comment]
Closing this issue. 

Tested and confirmed https://github.com/mattermost/mattermost-plugin-zoom/pull/73 resolves this case.
Thanks @larkox 🎉

**Comment by DHaussermann** [comment]
@hanzei  I'm not sure I access to close out issues but this can be closed.
