### ISSUE TITLE
Feature request: limit posting bot message to private channels only

### ISSUE THREAD

**Issue by vpecinka** [mattermost/mattermost-plugin-zoom#79]
It would be nice if we could limit creating invitation messages within private channels (or direct messages) only.

With many BFU posting invitations in public channels these become messy...

Thanks!

**Comment by levb** [comment]
@vpecinka Out of curiosity, would it be helpful to have a `/zoom protect [~channel]` (name TBD) to disable the posts on a per-channel basis? In addition to what I am assuming is an ask for a plugin-wide config setting **[X] Disable plugin posts in public channels**.

**Comment by vpecinka** [comment]
Yes, it would be great!

**Comment by larkox** [comment]
@aaronrothschild Just a cherry on top, you could check the status of the enable/disable with a settings panel, and change it on the fly. Something like `/zoom channelSettings` would open the settings panel for the channel you are in.

**Comment by aaronrothschild** [comment]
> @aaronrothschild Just a cherry on top, you could check the status of the enable/disable with a settings panel, and change it on the fly. Something like `/zoom channelSettings` would open the settings panel for the channel you are in.

The settings panel makes sense, and we should consider adding "Zoom settings" to the Channel Menu Bar as an option. But is it obvious enough there?

**Comment by larkox** [comment]
I remember a discussion not long ago about how some option that was on the channel menu bar was never found by users naturally. I wonder how much that can be solved by documentation, or we are dealing with a bigger UX problem.

Another solution (which may be quite bad) is to have a "settings button" on the same place as other plugin actions (next to the searchbar). The problem will be when 3 or 4 register their action button and the settings button, overpopulating that menu.

**Comment by larkox** [comment]
As a first approach, we would like to implement this as follow:
- One setting in the system console for the default behaviour. Something like `Disable the meeting creation on public channels?`
  - This setting should have a help text to inform about the slash commands defined below.
- One slash command only accessible to sysadmins to allow or deny creating meetings on a certain public channel. For example: `/zoom disable` and `/zoom enable` (these names are open (and encouraged) to suggestions)
  - These commands should not work on DM or Group messages
  - A `/zoom default` command could also be useful to reset the command to use default.
- One slash command (`/zoom list`) that list all the channels which has a setting different to default. This one should be also for sysadmins only. It should contain links to the channels.

**Comment by raghavaggarwal2308** [comment]
> One slash command only accessible to sysadmins to allow or deny creating meetings on a certain public channel. For example: /zoom disable and /zoom enable (these names are open (and encouraged) to suggestions)

@mickmister @larkox Just a suggestion, won't it be better to have a single command like `/zoom channelSettings` as suggested by @larkox above?

**Comment by mickmister** [comment]
@raghavaggarwal2308 Maybe we can do this:

Have a default setting in the system console to "restrict bot posting to only DM/GM and private channels". The default value for this setting will be `false`.

Then add these commands:
- `/zoom channel-settings` - Open modal to change settings for this channel. Allows user to select 1 of 3 booleans:
  - Enable
  - Disable
  - Default (and show what the plugin-wide default value is currently set to)
- `/zoom channel-settings list` - Output information for all channels that have settings applied

Each channel can have its own configuration stored in the plugin's KV store. If a given plugin's entry is missing, we'll treat it as "default".

**Comment by ayusht2810** [comment]
@mickmister Sounds good to me.
