### ISSUE TITLE
"undefined already created a zoom call recently"

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-plugin-zoom#85]
For some reason the name of the user who created a zoom call recently shows up as undefined.

**Comment by svelle** [comment]
Hi @ThiefMaster what Zoom Plugin version are you seeing this on?

**Comment by larkox** [comment]
Hi @ThiefMaster , this should be solved on this PR: https://github.com/mattermost/mattermost-plugin-zoom/pull/73

I do not have at the moment a date for the next fix version with this change, but I hope it is soon.

**Comment by hanzei** [comment]
Duplicates  https://github.com/mattermost/mattermost-plugin-zoom/issues/76
