### ISSUE TITLE
Client not updated on configuration change

### ISSUE THREAD

**Issue by larkox** [mattermost/mattermost-plugin-zoom#86]
After a configuration change, the apiKey and apiSecret may change. Nevertheless, this information is only used during the activation of a plugin to create the client, so after a configuration change the client is outdated, and may return "Invalid Token" errors.

**Comment by hanzei** [comment]
@larkox Do you want to work on this yourself or should it be a HW?

**Comment by larkox** [comment]
I can take it myself. I believe it should be solved soon.
