### ISSUE TITLE
"Start Zoom Meeting" button does not work, but /zoom start does

### ISSUE THREAD

**Issue by xsgb** [mattermost/mattermost-plugin-zoom#91]
Hello!

The procedure you wrote for setting up matttermost-plugin-zoom worked without any problem. We added some users in Zoom SaaS manager and now those users are able to type `/zoom start` to create Personal Meeting Identifier from the bot. 

All this worked correctly.

However, clicking the "Start Zoom Meeting" button on left of the search bar, we get:

> System
> 5:00 PM(Only visible to you)
> ×
> We could not verify your Mattermost account in Zoom. Please ensure that your Mattermost email address matches your Zoom email address.

Any Idea what would such error message ? Thanks in advance.

**Comment by larkox** [comment]
Can you confirm which version of the plugin are you using?

**Comment by xsgb** [comment]
It is `v1.3.0` installed from Mattermost's system console plugins marketplace.

**Comment by larkox** [comment]
Could you check the network panel on the browser?
There should be a call to `plugins/zoom/api/v1/meetings`. I am specially interested on the status code and the response.

**Comment by xsgb** [comment]
Yes! query part:

```
POST /plugins/zoom/api/v1/meetings HTTP/1.1
Host: fourjsmatter.xyz.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
X-CSRF-Token: ijznf4pae7ys8pqaq496f69a1a
Content-Type: text/plain;charset=UTF-8
Origin: https://fourjsmatter.xyz.com
Content-Length: 85
DNT: 1
Connection: keep-alive
Cookie: GeneroAuth=uid%3Dxasa%40xyz.com%3Bvaliduntil%3D1585303754%3Bgraceperiod%3D1585300154%3Btokens%3DjiraToken%2CfjsToken%2CamsToken%3Budata%3D%3Bsig%3DcdCTEh31atNpgG%2B7ezTqw3wym4bGAtZpp%2FtVah2Wb8ofdlAigXp5M4mEAnwatOtaFmUY0XMbG1czle%2BK8JFS3AI7YxKHKXMjIrUPiBA0OuGPedzWPgaBgh6W1dp%2FOffqi8t3EZ%2BMtx4qt4cKMO3mOCH9K6ZZ3qyr%2Bj0L4V1G46F2Md7TpVcs97fl7ZHgF%2Bt4wO2wKhYr8whfh%2FS%2F1%2FUt3SrfwoZdaWgN38uZW1DxdMYP78XztagYyJeDyQJgP%2FesZg%2BD2HNCdoM840ZWGV0I7%2BQ1wa2Z833fURlv2O9e2okjZjsswlIi5B7pChU%2F8WMLjPdLKK0yew%2Bv55dKTRJyyA%3D%3D
```

Response:

```
HTTP/2 301 Moved Permanently
server: nginx
date: Fri, 27 Mar 2020 09:28:33 GMT
content-type: text/html
content-length: 178
location: https://xyz.com
X-Firefox-Spdy: h2
```
Due to specific reverse proxy settings, we're redirecting everything that is not https://fourjsmatter.xyz.com/fourjsmatter to https://xyz.com

It seems thee plugin calls `https://fourjsmatter.xyz.com/plugins` instead of `https://fourjsmatter.xyz.com/fourjsmatter/plugins`

You you think this can be fixed in the plugin code ?
Thanks a lot for the time you're taking.

**Comment by larkox** [comment]
Yes, that should be something handled by the plugin. Just to confirm, the Site URL is correctly set to `https://fourjsmatter.xyz.com/fourjsmatter`, right? Not to `https://fourjsmatter.xyz.com/`.

**Comment by xsgb** [comment]
yes, the global site URL for this mattermost instance is set to `https://fourjsmatter.xyz.com/fourjsmatter`

**Comment by larkox** [comment]
I will try to have a fix included in the code by the end of the day. I will inform you whenever I know when this fix will be available in the marketplace.

**Comment by xsgb** [comment]
Ok! thanks a lot.

**Comment by larkox** [comment]
@xsgb If I am not mistaken, the updated version that corrects this should be already on the marketplace. Feel free to check it and let me know if you find any other issue.
