### ISSUE TITLE
Plugin uses incorrect path when mattermost siteurl has a subdir

### ISSUE THREAD

**Issue by sphr** [mattermost/mattermost-plugin-zoom#96]
The mattermost zoom plugin does not account for mattermost being able to run in a subdir.
This seems to be related to a bug I reported for mattermost server and they recommended a fix should be made for each plugin: https://github.com/mattermost/mattermost-server/issues/14106

A fix was applied for another plugin here:
https://github.com/standup-raven/standup-raven/issues/130

**Comment by hanzei** [comment]
@larkox I suppose this will be fixed with https://github.com/mattermost/mattermost-plugin-zoom/pull/93. Can you confirm?

**Comment by larkox** [comment]
Yes, that PR should fix the issue.
