### ISSUE TITLE
Zoom settings webhook secret

### ISSUE THREAD

**Issue by robormondsimpro** [mattermost/mattermost-plugin-zoom#97]
Hi,
I'm trying to set up the zoom plugin for the first time and I don't see anything in the docs about what I'm meant to do with the webhook secret in the plugin settings?

**Comment by terafirmanz** [comment]
Zoom process for Apps has been updated so I think the docs need updating. I also ran into this but it works without putting this setting anywhere.

**Comment by terafirmanz** [comment]
With 1.4 and the new docs this is now covered and can be closed can't it?

**Comment by larkox** [comment]
Closed due to newest version of the plugin and the documentation.
