### ISSUE TITLE
Meeting Password: Display when starting a new meeting

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-zoom#98]
If someone's settings specify that a Zoom meeting should use a password, currently the Plugin will not display the password after clicking "start Zoom meeting".

Ideally, if the user's account is set to have passwords enabled for each meeting - we should display the password when the meeting is created. 

Optionally, we should consider a slash command parameter for starting meetings with a password such as `/zoom start password 1234`

**Comment by terafirmanz** [comment]
Now required more than ever as Zoom move this setting to recommend and set this by default after the recent security reports.

**Comment by terafirmanz** [comment]
> Now required more than ever as Zoom move this setting to recommend and set this by default after the recent security reports.

Latest update from Zoom is this will be mandatory as of 9th May for Basic and 30th May for paid accounts meaning this plugin will become non functional as of these dates.

**Comment by aaronrothschild** [comment]
Yup, was just reviewing this in the Zoom PLugin channel, thanks for the heads up!  cc @larkox @levb

**Comment by s1lviu** [comment]
Any updates on this?

**Comment by larkox** [comment]
We are planning a release soon that will include this. We still not have a date for this, but we will try to have it ready as soon as possible.

**Comment by terafirmanz** [comment]
another closed now that we have 1.4 release?
